checker:
  b_debug: False
  capes:
    b_liquidbounce: False
    b_optifine: True
    b_labymod:  True
    b_minecon:  True
    b_5zig: True
  hypixel:
    i_method: 0
    #0 = api
    #1 = plank
    b_check_api_keys: True
    s_api_keys: 84848484|3242342 #not working atm
  rank:
    b_mineplex: True
    b_hypixel:  True
    b_hivemc: True
  level:
    b_hypixel: True
    b_mineplex: True
    i_minlevel_hypixel: 15
    i_minlevel_mineplex: 15
  threads:
    i_threads: 700 #threads for account checking
  proxy:
    b_proxy: True #if proxys should be used
    b_check: True #if proxys should be checked before using
    b_use_transparent: true #If true you should also use a vpn
proxy_checker:
  i_timeout: 10000 #Milleseconds
  i_threads: 1000
  i_recheck_amount: 0 #0 to disable this feature | not made yet omegalul
  s_proxy_judge: 'http://azenv.net/'
