checker:
  b_debug: False #normal user should keep it False
  i_check_amount: 2 #needs to be 1 or higher
  capes:
    b_liquidbounce: False
    b_optifine: True
    b_labymod:  True
    b_minecon:  True
    b_5zig: True
  hypixel:
    i_method: 0
    #0 = api
    #1 = plank
    b_check_api_keys: True #not made atm
  rank:
    b_mineplex: True
    b_hypixel:  True
    b_hivemc: True
  level:
    b_hypixel: True
    b_mineplex: True
    i_minlevel_hypixel: 15
    i_minlevel_mineplex: 15
  threads:
    i_threads: 400 #threads for account checking
  proxy:
    b_proxy: False #if proxies should be used
    b_check: False #if proxies should be checked before using
    s_proxy_type: 'http' #proxy types: http | https | socks4 | socks5
    b_use_transparent: true #If true you should also use a vpn
    b_use_api: false # if false it will use the proxies.txt | if true it will use the api link
    s_api_link: 'api.example.net/uiphdf12iu4'
proxy_checker:
  i_timeout: 10000 #Milleseconds
  i_threads: 1000
  s_proxy_judge: 'http://azenv.net/'
